#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use Harmless::M3U8;

print Harmless::M3U8->new->parse(
  do { local $/; <> }
)->format;

# vim:ts=2:sw=2:sts=2:et:ft=perl

